#install.packages(c("farver", "distributional", "fabletools", "feasts", "labeling", "ggplot2", "nonlinearTseries", "tseries"))
#install.packages("ggtime")
library(readr)
library(tsibble)
library(dplyr)
library(lubridate)
library(farver)
library(distributional)
library(fabletools)
library(feasts)
library(labeling)
library(ggplot2)
library(ggtime)
library(nonlinearTseries)
library(tseries)

cryptos_price <- read_csv("cryptos_price.csv")
print("Step 1")
View(cryptos_price)
str(cryptos_price)

print("Step 2")
cryptos_price$ds <- ymd(cryptos_price$ds)
print(unique(cryptos_price$coin))
iota_price <- cryptos_price |>
  filter(coin == "iota") |>
  mutate(ds = ymd(ds)) |>
  select(ds, y) |>
  distinct(ds, .keep_all = TRUE)
summary(iota_price)

print("Step 3")
iota_price <- as_tsibble(iota_price, key=NULL, index=ds)
str(iota_price)
glimpse(iota_price, width = 60)

print("Step 4")
png("price_data_plot.png", width = 800, height = 600)
plot(iota_price$ds, iota_price$y, type = "l")
dev.off()

print("Step 5")
# acf(iota_price$y)
# pacf(iota_price)
#ts_ap <- as_tsibble(iota_price, key = NULL, index = ds)
ts_ap <- iota_price
ts_ap |> gg_lag(geom = "point") + theme_minimal()
ts_ap |> ACF(lag_max = 6)
ts_ap |> ACF() |> autoplot() + theme_minimal()
ggsave("acf_plot.png", width = 20, height = 15, units = "cm")
ts_ap |> PACF() |> autoplot() + theme_minimal()
ggsave("pacf_plot.png", width = 20, height = 15, units = "cm")

print("Step 6")
nonlinearityTest(iota_price$y, verbose = TRUE)
adf.test(iota_price$y)
kpss.test(iota_price$y)
pp.test(iota_price$y)

print("Step 7")
tsData  <- ts(data = iota_price$y, start = c(2018, 1), frequency = 30)
stlData <- stl(tsData, s.window = "periodic")
par(mfrow = c(1, 2))
png("price_plot.png", width = 800, height = 600)
hist(iota_price$y, main = "Price", xlab = "iota Price", col="lightblue")
dev.off()
png("diff_plot.png", width = 800, height = 600)
hist(diff(iota_price$y), main = "Diff", xlab = "Price Change", col="lightgreen")
dev.off()
par(mfrow = c(1, 1))