data(mtcars)
print(?mtcars)
print("summary")
print(summary(mtcars))
print("max, min")
print(which.max(mtcars$hp))
print(which.min(mtcars$hp))
print("rownames")
print(rownames(mtcars)[which.max(mtcars$hp)])
print(rownames(mtcars)[which.min(mtcars$hp)])
print("mean, median, mode")
print(mean(mtcars$wt))
print(median(mtcars$wt))
print(sort(-table(mtcars$wt)))
print("quantile")
print(quantile(mtcars$wt))

print("max, min")
print(which.max(mtcars$qsec))
print(which.min(mtcars$qsec))
print("rownames")
print(rownames(mtcars)[which.max(mtcars$qsec)])
print(rownames(mtcars)[which.min(mtcars$qsec)])
print("mean, median, mode")
print(mean(mtcars$mpg))
print(median(mtcars$mpg))
print(sort(-table(mtcars$mpg)))
print("quantile")
print(quantile(mtcars$mpg))